CREATE TABLE acroyoga_elements (
    element_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    element_slug_id TEXT NOT NULL,
    element_name TEXT NOT NULL,
    element_thumb_url TEXT NOT NULL,
);