CREATE TABLE acroyoga_flows (
    flow_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    flow_title TEXT NOT NULL,
    flow_slug_title TEXT NOT NULL
    flow_sequence TEXT[] NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);