INSERT INTO acroyoga_elements (element_slug_id, element_name, element_thumb_url)
VALUES
  ('straddle-bat','Straddle Bat', 'https://i.ibb.co/0Bh1W9K/Straddle-Bat.png'),  
    ('bat','Bat', 'https://i.ibb.co/gSzQS0L/Bat.png'),  
    ('front-bird','Front Bird', 'https://i.ibb.co/0K3404P/Front-Bird.png'),  
    ('back-bird','Back Bird', 'https://i.ibb.co/vQGR97M/Reverse-Front-Bird.png'),  
    ('vishnus-couch','Vishnu''s Couch', 'https://i.ibb.co/yFhCxCX/Vishnus-Couch.png'),  
    ('floating-pashi','Floating Pashi', 'https://i.ibb.co/5L7JZrM/Floating-Pashi.png'),  
    ('reverse-shoulderstand','Reverse Shoulderstand', 'https://i.ibb.co/J7y88LR/Reverse-Shoulderstand.png'),  
    ('reverse-shoulderstand-split','Reverse Shoulderstand (split)', 'https://i.ibb.co/tQTvxS7/Reverse-Shoudlerstand-Split.png'),  
    ('shoulderstand-piked-straddle','Shoulderstand (piked straddle)', 'https://i.ibb.co/kyBYRVb/Shouderstand-Piked-Straddle.png'),  
    ('shoulderstand-straight','Shoulderstand (straight)', 'https://i.ibb.co/F4SvpSZ/Shoulderstand-Straight.png'),  
    ('reverse-star-straight','Reverse Star (straight)', 'https://i.ibb.co/HTXdCFD/Reverse-Star-Straight.png'),  
    ('free-star-straight','Free Star (straight)', 'https://i.ibb.co/4sCKMtn/Free-Star-Straight.png'),  
    ('free-star-open-straddle','Free Star (open straddle)', 'https://i.ibb.co/r66dQQX/Free-Star-Open-Straddle.png'),  
    ('star-straight','Star (straight)', 'https://i.ibb.co/Qft4Hrs/Star-Straight.png'),  
    ('star-tucked','Star (tucked)', 'https://i.ibb.co/9vNvWvh/Star-Tucked.png'),  
    ('star-piked','Star (piked)', 'https://i.ibb.co/xDB1rP1/Star-Piked.png'),  
    ('star-open-straddle','Star (open straddle)', 'https://i.ibb.co/bNTJx9V/Star-Open-Straddle.png'),  
    ('star-piked-straddle','Star (piked straddle)', 'https://i.ibb.co/Tv98nqD/Star-Piked-Straddle.png'),  
    ('reverse-back-plank','Reverse Back Plank', 'https://i.ibb.co/6w4YMPk/Reverse-Back-Plank.png'),  
    ('boat','Boat', 'https://i.ibb.co/wYKcQMq/Boat.png'),  
    ('back-plank','Back Plank', 'https://i.ibb.co/KGHB19F/Back-Plank.png'),  
    ('candle-stick','Candle Stick', 'https://i.ibb.co/sWsc16J/Candlestick.png'),  
    ('side-star','Side Star', 'https://i.ibb.co/jWSgpmD/Side-Star.png'),  
    ('side-star-supported','Side Star (supported)', 'https://i.ibb.co/r4zQG6H/Side-Star-Supported.png'),  
    ('reverse-star-double-stag','Reverse Star (double stag)', 'https://i.ibb.co/3SYNV2t/Reverse-Star-Double-Stag.png'),  
    ('reverse-throne','Reverse Throne', 'https://i.ibb.co/chWQRN0/Reverse-Throne.png'),  
    ('straddle-throne','Straddle Throne', 'https://i.ibb.co/h72h05j/Straddle-Throne.png'),  
    ('throne','Throne', 'https://i.ibb.co/0fxhtnV/Throne.png');